# Generated by Django 3.1.7 on 2021-03-01 08:41

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('user_name', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['email'], unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
