# Generated by Django 3.1.7 on 2021-03-02 06:59

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_user_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, validators=[common.validators.password_validator]),
        ),
    ]
